### ISSUE TITLE
TypeError: YClientsAPI.__init__() got an unexpected keyword argument 'debug'

### ISSUE THREAD

**Issue by sashafyodorov7** [CoolmixZero/yclients-api-python#3]
Hi) Maybe you can help me with it) I filled TOKEN/CID/FID

from yclients import YClientsAPI

TOKEN = "ba49d8299ab5fa481ee5a562e80ee..."
СID = '351...'
FID = '604...'

api = YClientsAPI(token=TOKEN, company_id=СID, form_id=FID, debug=True)

And this happening when trying to open the file in terminal

Traceback (most recent call last):
  File "/Users/af/Documents/PROJECTS/YCLIENTS/YclientsTest/yclients-api-python/api.py", line 8, in <module>
    api = YClientsAPI(token=TOKEN, company_id=СID, form_id=FID, debug=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: YClientsAPI.__init__() got an unexpected keyword argument 'debug'

**Comment by CoolmixZero** [comment]
Hi, that's my fault, I forgot to add debug parameter for YClientsAPI class :(
To fix your error just simply delete debug argument from this line:

```python
api = YClientsAPI(token=TOKEN, company_id=СID, form_id=FID, debug=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
and after initialization of api you can write:
```python
api.show_debugging()
```
Other way:
If you need to see debugging right now, you can copy this file:
https://github.com/CoolmixZero/yclients-api-python/blob/main/yclients/yclients.py

**Comment by sashafyodorov7** [comment]
I have updated the file "yclients.py" but hase the same error:

Traceback (most recent call last):
  File "/Users/af/Documents/PROJECTS/YCLIENTS/YclientsTest/yclients-api-python/example.py", line 11, in <module>
    api = YClientsAPI(token=TOKEN, company_id=СID, form_id=FID, debug=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: YClientsAPI.__init__() got an unexpected keyword argument 'debug'

Maybe I need to change something?

Thanks!

**Comment by CoolmixZero** [comment]
I've edited my previous comment, where you can find answer :)

**Comment by sashafyodorov7** [comment]
Извиняюсь, не прочитал текст после ссылки))

Подскажите такой вопрос. Есть такая задача - достать данные из вайклаентс в таблицы (клиенты/записи/финансы/услуги/в общем практически всю информацию) и поместить в sql базу, чтобы можно было выводить данные так как нужно (аналитика вайклаентс не совсем подходит). И так же вытащить таблицы из рекламы fb (это уже проще) и поместить в эту же базу данных, чтобы можно было составлять отчеты по зависимостям рекламы к записям и тд.

Смогли бы вы такое решить и сколько это будет стоить? Если удобно - можете написать в телеграм @fedorovcom

**Comment by CoolmixZero** [comment]
Про данные yclients:
Фактически все нужные команды описаны в документации, однако, из некоторых таблиц (например финансы), насколько я помню, данные не достать(не нужно было с неё данные доставать на тот момент, когда создавал парсер), поэтому нужно доделать функции для этого. А с sql, просто создайте таблицы в которых будут только нужные вам данные, такие как имя-фамилия-телефон (но без почты например).
Про фб:
Не очень понимаю, с какими данными тут придётся работать, тк не работал с рекламой фб, но скорее всего можно банально скачать excel файл со всеми данными, запарсить его как вам требуется и туже рансформированные данные отправить в sql датабазу.

Я бы с радостью согласился на эту работу, но, к сожалению, у меня сейчас очень мало свободного времени из-за работы с учёбой

**Comment by CoolmixZero** [comment]
Если вам не трудно, я бы хотел в больших подробностях узнать о задаче, может она не займёт много времени. Можете написать в тг: 
https://t.me/Coolmix22

**Comment by sashafyodorov7** [comment]
Хорошо, давайте соберу в голове как это все должно выглядеть и отпишусь) спасибо!
